server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: encadreurService
          uri: lb://ENCADREURSERVICE
          predicates:
            - Path=/encadreur/**
        - id: stagiaireService
          uri: lb://STAGIAIRESERVICE
          predicates:
            - Path=/stagiaire/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/


